matrix:
    include:
        - os: linux
          jdk: oraclejdk8
          before_script:
              - chmod u+x gradlew
          script:
              - ./gradlew build -PJS -PNATIVE
        - os: osx
          osx_image: xcode8
          before_script:
              - chmod u+x gradlew
          script:
              - ./gradlew build -PJS -PNATIVE
