language: java

os:
    - linux
    - osx

matrix:
    include:
        - os: linux
        jdk: oraclejdk8
        - os: osx
        osx_image: xcode8

before_install:
     - chmod +x gradlew

script:
    - ./gradlew build
