language: java

os:
    - linux
    - osx

matrix:
    include:
        - os: linux
        jdk: oraclejdk8
        - os: osx
        osx_image: xcode8

script:
    - chmod u+x ./gradlew
    - ./gradlew build
